### ISSUE TITLE
[TestNG] Reporter org.testng.reporters.JUnitReportReporter@55f616cf failed

### ISSUE THREAD

**Issue by Naumansh** [trivago/cucable-plugin#121]
**Describe the bug**
There appears to be some problem with execution using maven failsafe plugin as i see the subject error on executing the tests. 
Plugin in POM are as below:
    <build>
        <plugins>

            
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <skipTests>true</skipTests>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>${maven.failsafe.plugin.version}</version>
                <executions>
                    <execution>
                        <id>Run parallel tests</id>
                        <phase>integration-test</phase>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <threadCount>${threads}</threadCount>
                    <testFailureIgnore>true</testFailureIgnore>
                    <disableXmlReport>true</disableXmlReport>
                    <argLine>-Dfile.encoding=UTF-8</argLine>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven.compiler.plugin.version}</version>
                <configuration>
                    <source>8</source>
                    <target>8</target>
                </configuration>
            </plugin>
            
            <plugin>
                <groupId>com.trivago.rta</groupId>
                <artifactId>cucable-plugin</artifactId>
                <version>1.5.1</version>
                <executions>
                    <execution>
                        <id>generate-test-resources</id>
                        <phase>generate-test-resources</phase>
                        <goals>
                            <goal>parallel</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    
                    <sourceRunnerTemplateFile>src/test/java/sba/sbir/steps/CustomCreator.java</sourceRunnerTemplateFile>

                    
                    <sourceFeatures>src/test/resources/features</sourceFeatures>

                    
                    
                    
                    
                    

                    
                    

                    <generatedFeatureDirectory>${generated.feature.directory}</generatedFeatureDirectory>
                    <generatedRunnerDirectory>${generated.runner.directory}</generatedRunnerDirectory>

                    
                    
                    
                    

                    
                    <includeScenarioTags>${tags}</includeScenarioTags>
                   
                    

                    
                    <parallelizationMode>scenarios</parallelizationMode>
                    

                    
                    

                    
                    

                    
                    

                    
                    <logLevel>default</logLevel>
                    
                    
                    
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>${maven.build.helper.plugin.version}</version>
                <executions>
                    <execution>
                        <id>add-test-source</id>
                        <phase>generate-test-sources</phase>
                        <goals>
                            <goal>add-test-source</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <sources>
                        <source>${project.build.directory}/parallel/runners</source>
                    </sources>
                </configuration>
            </plugin>
        </plugins>

ERROR:

[TestNG] Reporter org.testng.reporters.XMLReporter@424e1977 failed
java.lang.NullPointerException
        at java.util.Hashtable.put(Hashtable.java:460)
        at java.util.Properties.setProperty(Properties.java:166)
        at org.testng.reporters.XMLSuiteResultWriter.getTestResultAttributes(XMLSuiteResultWriter.java:185)
        at org.testng.reporters.XMLSuiteResultWriter.addTestResult(XMLSuiteResultWriter.java:153)
        at org.testng.reporters.XMLSuiteResultWriter.addTestResults(XMLSuiteResultWriter.java:132)
        at org.testng.reporters.XMLSuiteResultWriter.writeAllToBuffer(XMLSuiteResultWriter.java:76)
        at org.testng.reporters.XMLSuiteResultWriter.writeSuiteResult(XMLSuiteResultWriter.java:54)
        at org.testng.reporters.XMLReporter.writeSuiteToBuffer(XMLReporter.java:134)
        at org.testng.reporters.XMLReporter.writeSuite(XMLReporter.java:96)
        at org.testng.reporters.XMLReporter.generateReport(XMLReporter.java:69)
        at org.testng.TestNG.generateReports(TestNG.java:1097)
        at org.testng.TestNG.run(TestNG.java:1022)
        at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
        at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
        at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
        at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
[TestNG] Reporter org.testng.reporters.jq.Main@36d585c failed
java.lang.NullPointerException
        at java.lang.StringBuilder.<init>(StringBuilder.java:112)
        at org.testng.reporters.jq.Model.getTestResultName(Model.java:139)
        at org.testng.reporters.jq.ChronologicalPanel.getContent(ChronologicalPanel.java:67)
        at org.testng.reporters.jq.BaseMultiSuitePanel.generate(BaseMultiSuitePanel.java:24)
        at org.testng.reporters.jq.Main.generateReport(Main.java:65)
        at org.testng.TestNG.generateReports(TestNG.java:1097)
        at org.testng.TestNG.run(TestNG.java:1022)
        at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
        at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
        at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
        at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
[TestNG] Reporter org.testng.reporters.JUnitReportReporter@55f616cf failed
java.lang.NullPointerException
        at java.util.Hashtable.put(Hashtable.java:460)
        at java.util.Properties.setProperty(Properties.java:166)
        at org.testng.reporters.JUnitReportReporter.createTestTagFor(JUnitReportReporter.java:216)
        at org.testng.reporters.JUnitReportReporter.generateReport(JUnitReportReporter.java:129)
        at org.testng.TestNG.generateReports(TestNG.java:1097)
        at org.testng.TestNG.run(TestNG.java:1022)
        at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
        at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
        at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
        at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.36 s <<< FAILURE! - in login_scenario001_run001_IT
[ERROR] null on login_scenario001_run001_IT(login_scenario001_run001_IT)  Time elapsed: 0.289 s  <<< FAILURE!
cucumber.runtime.CucumberException: java.lang.NoSuchMethodException: cucumber.runtime.java.JavaBackend.<init>(cucumber.runtime.io.ResourceLoader, io.cucumber.stepexpression.TypeRegistry)
Caused by: java.lang.NoSuchMethodException: cucumber.runtime.java.JavaBackend.<init>(cucumber.runtime.io.ResourceLoader, io.cucumber.stepexpression.TypeRegistry)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   login_scenario001_run001_IT » Cucumber java.lang.NoSuchMethodException: cucumb...
[INFO] 
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0

**Comment by laxersaz** [comment]
```
cucumber.runtime.CucumberException: java.lang.NoSuchMethodException: cucumber.runtime.java.JavaBackend.(cucumber.runtime.io.ResourceLoader, io.cucumber.stepexpression.TypeRegistry)
Caused by: java.lang.NoSuchMethodException: cucumber.runtime.java.JavaBackend.(cucumber.runtime.io.ResourceLoader, io.cucumber.stepexpression.TypeRegistry)
```

Seems to be a problem with your test framework or the test you are trying to run. Cucable just prepares the test resources and has nothing to do with running the tests.

**Comment by Naumansh** [comment]
Thanks man for responding back.

I doubt its framework problem as the execution fails even before reaching out to the framework. **The test at this stage has no step implementation and is supposed to generate gherkin step skeletons**. Also below message is coming up from failsafe somehow as TestNg is no where used as well and we can see some strange information in console as below:
[TestNG] Reporter org.testng.reporters.XMLReporter@424e1977 failed

I am pretty much familiar with this stuff asI have used teymers for very long in other project but its not maintained anymore. So, i planned to try with cucable. So, I certainly beleive its not a framework issue, as the error also shows

**Comment by laxersaz** [comment]
Have you tried the Cucable example project and does it work for you?
If a test cannot find the step implementation that could indicate that the glue path is incorrectly set. But again, this is not related to Cucable as it just prepares test resources, nothing else.
Have you had a closer look at the runners and features that Cucable generated and checked if those are correct?

**Comment by Naumansh** [comment]
So currently i didn't add any reporting at all. I am just trying to make sure that the basic structure is working fine before plug in anything else.

Below is the snippet of Runner class generated in parallel folder inside target
RunWith(Cucumber.class)
@CucumberOptions(
        glue = "src/test/java/sba/sbir/steps",
        features = {"target/parallel/features/login_scenario001_run001_IT.feature"},
        plugin = {"json:target/cucumber-report/login_scenario001_run001_IT.json"}
)
public class login_scenario001_run001_IT {

}

:: Earlier i tried using only the folder name in glue like "steps"

The error stays the same. Don't you think below line in Bold is the culprit

Caused by: java.lang.NoSuchMethodException: cucumber.runtime.java.JavaBackend.<init>(cucumber.runtime.io.ResourceLoader, **io.cucumber.stepexpression.TypeRegistry**)

**Comment by Naumansh** [comment]
Ok. I got the culprit. I have to use cucumber java dependency instead of cucumber jvm.
Thanks a lot man for your time.

**Comment by laxersaz** [comment]
Cool!
